using CaminhoLivre.Compartilhado.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CaminhoLivre.Infrastructure.Persistence.Configurations.Compartilhado;

public class EstadoMapping : IEntityTypeConfiguration<Estado>
{
    public void Configure(EntityTypeBuilder<Estado> builder)
    {
        //1. Nome da tabela no banco de dados  (padrão snake_case para o Postgres)
        builder.ToTable("estados");

        // 2. Chave Primária configurada como BIGINT autoincremento (Identity)
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id)
            .UseIdentityByDefaultColumn() // Cria como "GENERATED BY DEFAULT AS IDENTITY" no Postgres
            .HasColumnName("id");

        // 3. Mapeamento das Propriedades (Campos)
        builder.Property(c => c.Nome)
            .IsRequired() // Campo obrigatório
            .HasMaxLength(200) // Limite de caracteres
            .HasColumnName("nome"); // Nome da coluna no banco

        builder.Property(c => c.Sigla)
            .IsRequired()
           .HasMaxLength(2) // Limite de caracteres
           .HasColumnName("sigla"); // Nome da coluna no banco

        builder.HasMany(c => c.Municipios)
             .WithOne(m => m.Estado);

         builder.Navigation(c => c.Municipios)
            .UsePropertyAccessMode(PropertyAccessMode.Field); // Configura o EF para acessar a coleção de municipios via campo privado
    }
}
