using CaminhoLivre.Compartilhado.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CaminhoLivre.Infrastructure.Persistence.Configurations.Compartilhado;

public class MunicipioMapping : IEntityTypeConfiguration<Municipio>
{
    public void Configure(EntityTypeBuilder<Municipio> builder)
    {
        builder.ToTable("municipios");

        // 2. Chave Primária configurada como BIGINT autoincremento (Identity)
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id)
            .UseIdentityByDefaultColumn() // Cria como "GENERATED BY DEFAULT AS IDENTITY" no Postgres
            .HasColumnName("id");

        builder.Property(c => c.Nome)
            .IsRequired()
            .HasMaxLength(150)
            .HasColumnName("nome");

        builder.Property(c => c.CodigoIbge)
            .HasColumnName("codigo_ibge");

        builder.HasIndex(c => c.CodigoIbge)
             .IsUnique();

        //Relacionamento muitos municipios para um unico estado
        builder.HasOne(p => p.Estado)
               .WithMany(c => c.Municipios) 
               .HasForeignKey(p => p.EstadoId)
               .OnDelete(DeleteBehavior.Restrict) 
               .HasConstraintName("fk_municipios_estados_estado_id");

    }
}
