using CaminhoLivre.Modulo.Catalogo.Entities;
using Microsoft.EntityFrameworkCore;

namespace CaminhoLivre.Infrastructure.Persistence.Configurations.Catalogo;

public class CategoriaMapping : IEntityTypeConfiguration<Categoria>
{
    public void Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder<Categoria> builder)
    {
        //1. Nome da tabela no banco de dados  (padrão snake_case para o Postgres)
        builder.ToTable("categorias");

        // 2. Chave Primária configurada como BIGINT autoincremento (Identity)
        builder.HasKey(c => c.Id);
        builder.Property(c => c.Id)
            .UseIdentityByDefaultColumn() // Cria como "GENERATED BY DEFAULT AS IDENTITY" no Postgres
            .HasColumnName("id");

        // 3. Mapeamento das Propriedades (Campos)
        builder.Property(c => c.Nome)
            .IsRequired() // Campo obrigatório
            .HasMaxLength(100) // Limite de caracteres
            .HasColumnName("nome"); // Nome da coluna no banco

        builder.Property(c => c.Descricao)
            .HasMaxLength(500) // Limite de caracteres
            .HasColumnName("descricao"); // Nome da coluna no banco

        builder.Property(c => c.Ativo)
            .IsRequired()
            .HasDefaultValue(true) // Configura o valor padrão direto no banco
            .HasColumnName("ativo");

        builder.Property(c => c.DataCadastro)
            .IsRequired()
            .HasColumnName("data_cadastro");

        builder.Property(c => c.DataAlteracao)
            .HasColumnName("data_alteracao");

        builder.Property(c => c.Slug)
            .HasMaxLength(150)
            .HasColumnName("slug");

        builder.HasIndex(c => c.Slug).IsUnique(); // Índice único para o campo Slug, garantindo que não haja duplicatas

        // 5. Configuração do Relacionamento (1 Categoria para Muitos Produtos)
        // Avisa o EF Core para ignorar a propriedade pública e injetar dados direto no campo privado '_produtos'
        builder.HasMany(c => c.Produtos)
            .WithOne()// Se o Produto não tiver a propriedade "Categoria" de navegação inversa
            .HasForeignKey("categoria_id")// Cria a FK oculta ou explícita na tabela de produtos
            .OnDelete(DeleteBehavior.Restrict);// Impede deletar uma categoria que possui produtos vinculados

        builder.Navigation(c => c.Produtos)
            .UsePropertyAccessMode(PropertyAccessMode.Field); // Configura o EF para acessar a coleção de produtos via campo privado
    }
}
