using CaminhoLivre.Modulo.Catalogo.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CaminhoLivre.Infrastructure.Persistence.Configurations.Catalogo;

public class ProdutoMapping : IEntityTypeConfiguration<Produto>
{
    public void Configure(EntityTypeBuilder<Produto> builder)
    {
        // 1. Nome da tabela no banco de dados (padrão snake_case)
        builder.ToTable("produtos");

        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id)
            .UseIdentityByDefaultColumn() // Configura como "GENERATED BY DEFAULT AS IDENTITY" no Postgres
            .HasColumnName("id");

        builder.Property(p => p.Sku)
            .IsRequired().
            HasMaxLength(50)
            .HasColumnName("sku");

        builder.Property(p => p.Nome)
            .IsRequired()
            .HasMaxLength(150)
            .HasColumnName("nome");

        builder.Property(p => p.Descricao)
            .IsRequired()
            .HasMaxLength(1000)
            .HasColumnName("descricao");

        builder.Property(p => p.CodigoBarras)
            .HasMaxLength(20)
            .HasColumnName("codigo_barras");

        builder.Property(p => p.Moeda)
            .HasMaxLength(3)
            .HasDefaultValue("BRL")
            .HasColumnName("moeda");

        builder.Property(p => p.Ncm)
            .HasMaxLength(8)
            .HasColumnName("ncm");

        // 4. Mapeamento de Valores Numéricos e Decimais (Precisão monetária)
        builder.Property(p => p.PrecoCusto)
            .HasColumnType("numeric(18,2)")
            .IsRequired()
            .HasColumnName("preco_custo");

        builder.Property(p => p.PrecoVenda)
            .HasColumnType("numeric(18,2)")
            .IsRequired()
            .HasColumnName("preco_venda");

        builder.Property(p => p.PrecoPromocional)
            .HasColumnType("numeric(18,2)")
            .HasColumnName("preco_promocional");

        builder.Property(p => p.PesoBruto)
            .HasColumnType("numeric(18,3)")
            .HasColumnName("peso_bruto");

        builder.Property(p => p.Origem)
            .HasColumnName("origem");

        builder.Property(p => p.Ativo)
            .IsRequired()
            .HasDefaultValue(true)
            .HasColumnName("ativo");

        builder.Property(p => p.DataCadastro)
            .IsRequired()
            .HasColumnName("data_cadastro");

        builder.Property(p => p.DataAlteracao)
            .HasColumnName("data_alteracao");

        // 6. Índices de Performance e Unicidade
        // Garante que o SKU nunca se repita no banco de dados
        builder.HasIndex(p => p.Sku)
               .IsUnique();

        // 7. Relacionamento (Muitos Produtos para 1 Categoria)
        builder.HasOne(p => p.Categoria)
               .WithMany(c => c.Produtos) // Conversa direto com a lista mapeada na Categoria
               .HasForeignKey(p => p.CategoriaId)
               .OnDelete(DeleteBehavior.Restrict) // Segurança: impede deletar categoria com produto dentro
               .HasConstraintName("fk_produtos_categorias_categoria_id");
    }
}
